### ISSUE TITLE
Code for converting depth to TSDF

### ISSUE THREAD

**Issue by anhquancao** [charlesCXK/TorchSSC#10]
Hi,

Congrats on the good work. Could share the code to calculate the TSDF from the depth image?
I try to compute the TSDF from the TSDF by myself and feed it into your network but I cannot get the same results as using your provided TSDF.

Thank you very much.

**Comment by charlesCXK** [comment]
Hi, sorry for the late reply. I recommend referring to [SATNet](https://github.com/ShiceLiu/SATNet/blob/master/util/pre-get_training_data/test.sh) for the TSDF generation. 😀
