### ISSUE TITLE
Visualization of the results

### ISSUE THREAD

**Issue by keremyldrr** [charlesCXK/TorchSSC#12]
Hi, I have trained a model with the given introductions in the repository and achieved the described qualitative results. However, when I want to visualize the results I get a 3d grid full of noise. In order to visualize, I traverse all the (60,36,60) volume cells and color the object depending on their semantic label, which is the value of the voxel. Could you clarify how you exactly visualize your results such that i can fix this problem? First image is the snapshot for labels (i read it from numpy file and reshape it into (60,36,60). Second image is from the results generated by eval.py.
![snapshot00](https://user-images.githubusercontent.com/33193784/143425369-b0827cd8-1896-4168-b221-85d976614f17.png)
![snapshot01](https://user-images.githubusercontent.com/33193784/143425372-fb2ed664-59c2-434d-9672-08f3b228842d.png)

**Comment by anhquancao** [comment]
Hi @keremyldrr,
I have had this problem before. 3DSketch assumes the empty voxels are known and is trained only on the occluded and surface voxels of the scene.
You should set all the empty voxels explicitly using the **selectindex** obtained as in the following line
https://github.com/charlesCXK/TorchSSC/blob/master/model/sketch.nyu/train.py#L168

**Comment by keremyldrr** [comment]
Thanks for the heads up! It's more meaningful now.
