### ISSUE TITLE
No code released.

### ISSUE THREAD

**Issue by renaissanceFinFan** [charlesCXK/TorchSSC#2]
I have read your CVPR'2020. Both the idea and the results are impressive. Will you release the code of this paper recently?

**Comment by charlesCXK** [comment]
Thanks for your attention. We will make our code and data public **no later than** the end of this year. Our plan is to release a unified framework, which contains multiple models such as SSCNet, DDRNet and our SketchAwareSSC. We'll do it as soon as possible!

**Comment by charlesCXK** [comment]
@renaissanceFinFan Our code and data on NYU dataset has been released.
