### ISSUE TITLE
NYUCAD/SUNCG datasets

### ISSUE THREAD

**Issue by JennyVVV** [charlesCXK/TorchSSC#3]
Hi, thanks for your amazing jobs, could you provide the corresponding NYUCAD/SUNCG datasets?

**Comment by charlesCXK** [comment]
Hi, thanks for your attention, we are working on this.

**Comment by JennyVVV** [comment]
> Hi, thanks for your attention, we are working on this.

So how to generate the mapping index? I want to test different datasets, but I don't know how to generate corresponding data.

**Comment by charlesCXK** [comment]
@JennyVVV 
Sorry for the late reply. The mapping index tells us such thing: for a given index i in the 3D volume space, which index in the 2D image space does it corresponding to? Thus you could calculate such correspondence using the depth map and camera matrix.
