### ISSUE TITLE
Code for generating sketch

### ISSUE THREAD

**Issue by anhquancao** [charlesCXK/TorchSSC#9]
Hello,

Thank you for your work.
Could you provide the code you use to generate the sketch?

Thank you very much.

**Comment by crockwell** [comment]
@anhquancao were you able to find this out by any chance? This would be really helpful to share, thanks!

**Comment by anhquancao** [comment]
@crockwell check this link
https://github.com/charlesCXK/TorchSSC/issues/5

**Comment by crockwell** [comment]
thanks!
